##数据库各种使用场景及SQL规范请参考：http://doc.io/infrastructure/database/overview.html
##写库数据源
#datasource.common:
#  url: jdbc:mysql://10.10.35.162:6606/personnel?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
#  username: se
#  password: 123456
##  driverClassName: com.mysql.cj.jdbc.Driver
#  driverClassName: com.mysql.jdbc.Driver
#  max-active: 10                #最大活跃连接数
#  max-idle: 1                   #最大空闲连接数
#  min-idle: 1                   #最小空闲连接数
#  initial-size: 1               #初始连接数
#  max-wait: 10000               #从连接池获取可用连接的等待时长，单位毫秒
#  testWhileIdle: true           #开启检测空闲连接是否可用
#  validationQuery: select 1     #检测时执行的SQL
#  validationQueryTimeout: 1     #ValidationQuery执行超时时间，单位秒
#  validationInterval: 120000    #同一个连接执行连接可用性检测的间隔，单位毫秒
#
##只读库数据源
#datasource.readonly:
#  url: jdbc:mysql://10.10.35.162:6606/personnel?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
#  username: se
#  password: 123456
##  driverClassName: com.mysql.cj.jdbc.Driver
#  driverClassName: com.mysql.jdbc.Driver
#  max-active: 10                #最大活跃连接数
#  max-idle: 1                   #最大空闲连接数
#  min-idle: 1                   #最小空闲连接数
#  initial-size: 1               #初始连接数
#  max-wait: 10000               #从连接池获取可用连接的等待时长，单位毫秒
#  testWhileIdle: true           #开启检测空闲连接是否可用
#  validationQuery: select 1     #检测时执行的SQL
#  validationQueryTimeout: 1     #ValidationQuery执行超时时间，单位秒
#  validationInterval: 120000    #同一个连接执行连接可用性检测的间隔，单位毫秒
#数据库各种使用场景及SQL规范请参考：http://doc.io/infrastructure/database/overview.html
#写库数据源
datasource.common:
  url: jdbc:mysql://127.0.0.1:3306/zhumiao?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&useSSL=true
  username: root
  password: AF2a54c26646
#  driverClassName: com.mysql.cj.jdbc.Driver
  driverClassName: com.mysql.jdbc.Driver
  max-active: 10                #最大活跃连接数
  max-idle: 1                   #最大空闲连接数
  min-idle: 1                   #最小空闲连接数
  initial-size: 1               #初始连接数
  max-wait: 10000               #从连接池获取可用连接的等待时长，单位毫秒
  testWhileIdle: true           #开启检测空闲连接是否可用
  validationQuery: select 1     #检测时执行的SQL
  validationQueryTimeout: 1     #ValidationQuery执行超时时间，单位秒
  validationInterval: 120000    #同一个连接执行连接可用性检测的间隔，单位毫秒

#只读库数据源
datasource.readonly:
  url: jdbc:mysql://127.0.0.1:3306/zhumiao?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&useSSL=true
  username: root
  password: AF2a54c26646
#  driverClassName: com.mysql.cj.jdbc.Driver
  driverClassName: com.mysql.jdbc.Driver
  max-active: 10                #最大活跃连接数
  max-idle: 1                   #最大空闲连接数
  min-idle: 1                   #最小空闲连接数
  initial-size: 1               #初始连接数
  max-wait: 10000               #从连接池获取可用连接的等待时长，单位毫秒
  testWhileIdle: true           #开启检测空闲连接是否可用
  validationQuery: select 1     #检测时执行的SQL
  validationQueryTimeout: 1     #ValidationQuery执行超时时间，单位秒
  validationInterval: 120000    #同一个连接执行连接可用性检测的间隔，单位毫秒